apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  #Forward Proxy
  name: HTTP_PROXY
  value: "http://your-proxy-server:port"
  name: HTTPS_PROXY
  value: "https://your-proxy-server:port"
  name: NO_PROXY
  value: "localhost,127.0.0.1,argocd-server,argocd-repo-server,argocd-application-controller,argocd-redis"
  #SSO
  url: https://argocd.example.com
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: <your-github-client-id>
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: your-github-org
  oidc.config: |
    name: Dex
    issuer: https://dex.example.com
    clientID: argocd
    clientSecret: $oidc.dex.clientSecret